### ISSUE TITLE
Typo in EmployeeController.ts

### ISSUE THREAD

**Issue by patelkarn** [Giancarlo1974/SailsAngular#1]
import { Model } from 'Sails';

Sails need to be lower case 'sails'

**Comment by Giancarlo1974** [comment]
I think that you have some problem into typescript editor.
The editor does not see the sails typescript into my_module

**Comment by patelkarn** [comment]
I am not sure on that but after I changed to lower case sails. I was able to run node app.js and everything worked as expected.

**Comment by Giancarlo1974** [comment]
Can you post your modified EmployeeController.ts?
Which version of node you use?

**Comment by Giancarlo1974** [comment]
I developed the project using node js v8.2.1
